import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { enGB, enUS, de } from "../translations";

export default function Home() {
  const router = useRouter();
  const { locale } = router;

  const t = locale === "en-GB" ? enGB : locale === "en-US" ? enUS : de;

  const handleLanguageToggle = (lang) => {
    console.log(lang);
    router.push("/", "/", { locale: lang });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t.welcome} to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <select
          className="form-select"
          aria-label="Default select example"
          onChange={(e) => handleLanguageToggle(e.target.value)}
        >
          <option defaultValue="en-GB">en-GB</option>
          <option value="en-US">en-US</option>
          <option value="de">de</option>
        </select>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
